spring.application.name=backend

# Settingan Database H2 (In-Memory)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Biar console H2 bisa dibuka di browser
spring.h2.console.enabled=true

# Port Server (Default 8080, ditulis biar jelas aja)
server.port=8080